version: "3"

services:
    db:
        image: mariadb
        environment: 
            MYSQL_DATABASE: sanplan-database
            MYSQL_ROOT_PASSWORD: sanplan-password
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb_data:/var/lib/mysql
    web:
        build:
            context: ./web/
            dockerfile: Dockerfile
        env_file:
            - ./web/web.dev.env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./web:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            
