name: style-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Checking coding style
        run: cd web/ && flake .
